Set Shell fish
Set Height 800
Output paginator-tape.gif
Type "./paginator"
Sleep 500ms
Enter
Sleep 1s
Right
Sleep 200ms
Right
Sleep 200ms
Right
Sleep 200ms
Right
Sleep 200ms
Right
Sleep 200ms
Right
Sleep 200ms
Right
Sleep 200ms
Right
Sleep 200ms
Right
Sleep 3s
Left
Sleep 200ms
Left
Sleep 200ms
Left
Sleep 200ms
Left
Sleep 200ms
Left
Sleep 200ms
Left
Sleep 200ms
Left
Sleep 200ms
Left
Sleep 200ms
Left
Sleep 200ms
Sleep 5s